gui:
  showBottomLine: false
  showIcons: true
  theme:
    selectedLineBgColor:
      - default
    unstagedChangesColor:
      - yellow
os:
  editCommand: "nvr --remote-tab"
  openCommand: 'nvr'
promptToReturnFromSubprocess: false
