format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $cmd_duration\
  $custom\
  $line_break\
  $jobs\
  $battery\
  $time\
  $character\
  """
# $git_commit\
# $git_state\
# $git_status\
