alias so='source ~/.config/bash/config.fish'
alias se='nvim ~/.config/bash/config.fish'

alias cdw='cd /var/www/'
alias pu='./vendor/bin/phpunit'

alias art='php artisan '

alias gpu='git push'
alias gpl='git pull'
alias gs='git status'
alias gf='git fetch'
alias ga='git add'
alias gc='git commit'
alias gl='git log --oneline'
alias gtags='ctags -R --exclude=node_modules --exclude=.git --exclude=tests'

# update path
set PATH /home/shxfee/.composer/vendor/bin $PATH
